server:
  port: 8084

spring:
  application:
    name: parser
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: root

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: parser-consumer-group

parser:
  kafka:
    topic: "scan-job"

logging:
  level:
    org:
      apache:
        kafka: ERROR
      springframework:
        kafka: ERROR
    kafka: ERROR
